"""Added file upload for baseball card model

Revision ID: 43df2a50e5a8
Revises: 98799bfc1507
Create Date: 2024-07-27 00:28:12.019592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43df2a50e5a8'
down_revision = '98799bfc1507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseball_cards', sa.Column('picture', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baseball_cards', 'picture')
    # ### end Alembic commands ###
