"""Added new model

Revision ID: 98799bfc1507
Revises: 201b1b385790
Create Date: 2024-07-26 23:16:27.949826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98799bfc1507'
down_revision = '201b1b385790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseball_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('team', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baseball_cards')
    # ### end Alembic commands ###
